import PyRVC as RVC

print("Device.Create:", hasattr(RVC.Device, "Create"))
print("=== Device all ===")
print([m for m in dir(RVC.Device) if not m.startswith("_")])
print("=== X1 ===")
print([m for m in dir(RVC.X1) if not m.startswith("_")])
print("=== X2 ===")
print([m for m in dir(RVC.X2) if not m.startswith("_")])
print("=== Image ===")
print([m for m in dir(RVC.Image) if not m.startswith("_")])
print("=== PointMap ===")
print([m for m in dir(RVC.PointMap) if not m.startswith("_")])
print("=== ImageTypeEnum ===")
print([m for m in dir(RVC.ImageTypeEnum) if not m.startswith("_")])
print("=== PointMapTypeEnum ===")
print([m for m in dir(RVC.PointMapTypeEnum) if not m.startswith("_")])
print("=== GigE ===")
print([m for m in dir(RVC.GigE) if not m.startswith("_")])
print("=== System funcs ===")
print([m for m in dir(RVC) if m.startswith("System")])
print("=== X2_CaptureOptions ===")
o2 = RVC.X2_CaptureOptions()
print([a for a in dir(o2) if not a.startswith("_")])
