# Generated by Django 6.0.6 on 2026-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('device_code', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('transform_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.product')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='vision/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('vision_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vision.visiontask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RackLocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(max_length=16)),
                ('offset_x', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('offset_y', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('offset_z', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('measured_layer_height', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('measured_layer_spacing', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('recipe_layer_height', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('recipe_layer_spacing', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_recipe_matched', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.rack')),
                ('vision_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_results', to='vision.visiontask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoamInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_index', models.PositiveIntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('is_aligned', models.BooleanField(default=False)),
                ('has_lifted_edge', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('is_passed', models.BooleanField(default=False)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.product')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.rack')),
                ('vision_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foam_results', to='vision.visiontask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
