# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racklocationresult',
            name='side',
            field=models.CharField(choices=[('LEFT', '左侧'), ('RIGHT', '右侧'), ('BOTH', '双侧')], max_length=16),
        ),
        migrations.AlterField(
            model_name='visionimage',
            name='image_type',
            field=models.CharField(choices=[('ORIGINAL', '原图'), ('DEPTH', '深度图'), ('RESULT', '结果图')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visiontask',
            name='task_type',
            field=models.CharField(choices=[('RACK_LOCATING', '料架定位'), ('FOAM_INSPECTION', '泡棉检测'), ('SCAN_ASSIST', '扫码辅助')], max_length=64),
        ),
    ]
