# Generated by Django 5.2.8 on 2026-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_alter_racklocationresult_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foaminspectionresult',
            name='coverage_ratio',
            field=models.DecimalField(decimal_places=4, default=0, help_text='泡棉覆盖率', max_digits=5),
        ),
        migrations.AddField(
            model_name='foaminspectionresult',
            name='defect_type',
            field=models.CharField(default='NONE', help_text='缺陷类型', max_length=32),
        ),
        migrations.AddField(
            model_name='foaminspectionresult',
            name='offset_x_px',
            field=models.DecimalField(decimal_places=2, default=0, help_text='X轴偏移（像素）', max_digits=10),
        ),
        migrations.AddField(
            model_name='foaminspectionresult',
            name='offset_y_px',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Y轴偏移（像素）', max_digits=10),
        ),
    ]
