# Generated by Django 6.0.6 on 2026-06-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_status_and_more'),
        ('dm_camera', '0001_initial'),
        ('vision', '0004_visionrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='racklocationresult',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='layer_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='offset_rz',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='actual_x',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='actual_y',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='actual_z',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='plc_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='plc_write_status',
            field=models.CharField(default='SKIPPED', max_length=32),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='position_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='raw_data_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='result_image_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='RackLocationRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_name', models.CharField(max_length=128, unique=True)),
                ('rack_type', models.CharField(blank=True, max_length=64)),
                ('rack_side', models.CharField(choices=[('LEFT', '左侧'), ('RIGHT', '右侧'), ('BOTH', '双侧')], default='BOTH', help_text='保留兼容字段；现场不区分左右时使用 BOTH。', max_length=16)),
                ('position_no', models.PositiveIntegerField(db_index=True, default=1)),
                ('layer_count', models.PositiveIntegerField(default=3)),
                ('layer_no', models.PositiveIntegerField(db_index=True, default=1)),
                ('capture_pose_name', models.CharField(blank=True, max_length=128)),
                ('standard_x', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('standard_y', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('standard_z', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('standard_rz', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('roi_config', models.JSONField(blank=True, default=dict)),
                ('reference_feature_config', models.JSONField(blank=True, default=dict)),
                ('hand_eye_config', models.JSONField(blank=True, default=dict)),
                ('max_offset_x', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('max_offset_y', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('max_offset_z', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('max_offset_rz', models.DecimalField(decimal_places=3, default=5, max_digits=10)),
                ('confidence_threshold', models.DecimalField(decimal_places=4, default=0.7, max_digits=5)),
                ('enabled', models.BooleanField(default=True)),
                ('camera_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_location_recipes', to='dm_camera.dmcameraconfig')),
                ('camera_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_location_recipes', to='devices.device')),
            ],
            options={
                'ordering': ['position_no', 'layer_no', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='racklocationresult',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='vision.racklocationrecipe'),
        ),
        migrations.AddIndex(
            model_name='racklocationrecipe',
            index=models.Index(fields=['position_no', 'layer_no', 'enabled'], name='vision_rack_positio_892319_idx'),
        ),
    ]
