# Generated by Django 6.0.6 on 2026-06-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_status_and_more'),
        ('dm_camera', '0001_initial'),
        ('vision', '0006_add_actual_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackLocationROI3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roi_name', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[('global', '全局定位'), ('local', '局部定位')], max_length=16)),
                ('layer_no', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('coordinate_system', models.CharField(default='rack', max_length=32)),
                ('x_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('x_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('y_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('y_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('z_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('z_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['recipe_id', 'mode', 'layer_no', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='racklocationrecipe',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('position_no', 'layer_no'), name='unique_enabled_recipe_per_position_layer'),
        ),
        migrations.AddField(
            model_name='racklocationroi3d',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois_3d', to='vision.racklocationrecipe'),
        ),
        migrations.AddIndex(
            model_name='racklocationroi3d',
            index=models.Index(fields=['recipe', 'mode', 'layer_no', 'enabled'], name='vision_rack_recipe__8eec49_idx'),
        ),
        migrations.AddConstraint(
            model_name='racklocationroi3d',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True), ('mode', 'global')), fields=('recipe',), name='unique_enabled_global_3d_roi_per_recipe'),
        ),
        migrations.AddConstraint(
            model_name='racklocationroi3d',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True), ('mode', 'local')), fields=('recipe', 'layer_no'), name='unique_enabled_local_3d_roi_per_recipe_layer'),
        ),
        migrations.AddConstraint(
            model_name='racklocationroi3d',
            constraint=models.CheckConstraint(condition=models.Q(('x_min__lt', models.F('x_max'))), name='rack_3d_roi_x_min_lt_x_max'),
        ),
        migrations.AddConstraint(
            model_name='racklocationroi3d',
            constraint=models.CheckConstraint(condition=models.Q(('y_min__lt', models.F('y_max'))), name='rack_3d_roi_y_min_lt_y_max'),
        ),
        migrations.AddConstraint(
            model_name='racklocationroi3d',
            constraint=models.CheckConstraint(condition=models.Q(('z_min__lt', models.F('z_max'))), name='rack_3d_roi_z_min_lt_z_max'),
        ),
    ]
