# Generated by Django 5.2.8 on 2026-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_racklocationroi3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foaminspectionresult',
            name='offset_x_mm',
            field=models.DecimalField(decimal_places=3, default=0, help_text='X轴偏移（毫米，由 mm_per_pixel 标定系数换算）', max_digits=10),
        ),
        migrations.AddField(
            model_name='foaminspectionresult',
            name='offset_y_mm',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Y轴偏移（毫米，由 mm_per_pixel 标定系数换算）', max_digits=10),
        ),
    ]
