# Generated by Django 5.2.8 on 2026-06-30 12:11

from django.db import migrations


class Migration(migrations.Migration):
    """
    验证 RackLocationRecipe 模型字段完整性。
    
    任务 1.2: 扩展RackLocationRecipe模型
    - 验证所需字段已存在：
      * hand_eye_config (JSONField) ✓
      * reference_feature_config (JSONField) ✓
      * confidence_threshold (DecimalField, max_digits=5, decimal_places=4) ✓
      * standard_x, standard_y, standard_z (DecimalField, max_digits=10, decimal_places=3) ✓
      * max_offset_x, max_offset_y, max_offset_z (DecimalField, max_digits=10, decimal_places=3) ✓
    
    所有必需字段已在之前的迁移中创建，此迁移用于标记验证完成。
    Requirements: 10.1, 10.2, 19.4, 19.5
    """

    dependencies = [
        ('vision', '0008_foaminspectionresult_offset_x_mm_and_more'),
    ]

    operations = [
        # 所有必需字段已存在，无需添加新字段
    ]
