# Generated by Django 5.2.8 on 2026-06-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0010_extend_rack_location_result_model'),
    ]

    operations = [
    ]
