# Generated by Django 5.2.8 on 2026-07-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_status_and_more'),
        ('dm_camera', '0001_initial'),
        ('vision', '0011_task_1_3_racklocationroi3d_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='racklocationrecipe',
            name='capture_pose',
            field=models.JSONField(blank=True, default=dict, help_text='机器人拍照位姿 {"x": 0, "y": 0, "z": 0, "rx": 0, "ry": 0, "rz": 0}'),
        ),
        migrations.AlterField(
            model_name='racklocationrecipe',
            name='hand_eye_config',
            field=models.JSONField(blank=True, default=dict, help_text='已废弃，请使用hand_eye_calibration外键'),
        ),
        migrations.CreateModel(
            name='HandEyeCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='例如：装箱机器人-DM相机-20260101', max_length=128, unique=True, verbose_name='标定名称')),
                ('T_flange_camera', models.JSONField(default=dict, help_text='相机坐标系到机器人法兰坐标系的4×4齐次变换矩阵', verbose_name='手眼标定矩阵')),
                ('calibration_error', models.FloatField(default=0.0, help_text='标定重投影误差（单位：mm）', verbose_name='标定误差')),
                ('sample_count', models.IntegerField(default=0, help_text='用于标定的样本姿态数量', verbose_name='样本数量')),
                ('calibration_method', models.CharField(choices=[('OPENCV_TSAI', 'OpenCV Tsai-Lenz方法'), ('OPENCV_PARK', 'OpenCV Park方法'), ('OPENCV_HORAUD', 'OpenCV Horaud方法'), ('OPENCV_ANDREFF', 'OpenCV Andreff方法'), ('OPENCV_DANIILIDIS', 'OpenCV Daniilidis方法'), ('MANUAL', '手动输入'), ('VENDOR_TOOL', '厂商工具')], default='OPENCV_TSAI', max_length=32, verbose_name='标定方法')),
                ('calibration_params', models.JSONField(blank=True, default=dict, help_text='标定过程的详细参数记录', verbose_name='标定参数')),
                ('is_active', models.BooleanField(default=False, help_text='当前激活的标定配置，每组机器人-相机只能有一个激活的标定', verbose_name='是否激活')),
                ('verified_at', models.DateTimeField(blank=True, help_text='标定验证通过的时间', null=True, verbose_name='验证时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='操作员')),
                ('camera_device', models.ForeignKey(help_text='关联的3D深度相机设备', on_delete=django.db.models.deletion.CASCADE, related_name='hand_eye_calibrations_camera', to='devices.device', verbose_name='相机设备')),
                ('robot_device', models.ForeignKey(help_text='关联的机器人设备', on_delete=django.db.models.deletion.CASCADE, related_name='hand_eye_calibrations_robot', to='devices.device', verbose_name='机器人设备')),
            ],
            options={
                'verbose_name': '手眼标定',
                'verbose_name_plural': '手眼标定',
                'db_table': 'vision_hand_eye_calibration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='racklocationrecipe',
            name='hand_eye_calibration',
            field=models.ForeignKey(blank=True, help_text='关联的手眼标定配置，用于坐标转换', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_location_recipes', to='vision.handeyecalibration'),
        ),
        migrations.CreateModel(
            name='HandEyeCalibrationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_index', models.IntegerField(help_text='样本采集顺序', verbose_name='样本序号')),
                ('T_base_flange', models.JSONField(help_text='机器人法兰在基坐标系下的4×4变换矩阵或六自由度位姿', verbose_name='机器人位姿')),
                ('T_camera_target', models.JSONField(help_text='标定板在相机坐标系下的位姿（OpenCV格式或4×4矩阵）', verbose_name='标定板位姿')),
                ('detection_success', models.BooleanField(default=True, help_text='标定板特征点是否成功检测', verbose_name='检测成功')),
                ('reprojection_error', models.FloatField(default=0.0, help_text='该样本的特征点重投影误差（单位：像素）', verbose_name='重投影误差')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='vision.handeyecalibration', verbose_name='所属标定')),
                ('capture_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hand_eye_samples', to='dm_camera.dmcapturerecord', verbose_name='采集记录')),
            ],
            options={
                'verbose_name': '手眼标定样本',
                'verbose_name_plural': '手眼标定样本',
                'db_table': 'vision_hand_eye_sample',
                'ordering': ['calibration', 'sample_index'],
            },
        ),
        migrations.CreateModel(
            name='HandEyeVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('T_base_flange', models.JSONField(help_text='验证时的机器人位姿', verbose_name='机器人位姿')),
                ('test_points_camera', models.JSONField(help_text='相机坐标系下的测试点', verbose_name='相机坐标点')),
                ('test_points_robot', models.JSONField(help_text='转换后的机器人坐标系点', verbose_name='机器人坐标点')),
                ('ground_truth_points', models.JSONField(blank=True, default=list, help_text='已知的真实坐标（如有）', verbose_name='真实坐标点')),
                ('mean_error', models.FloatField(default=0.0, help_text='平均位置误差（单位：mm）', verbose_name='平均误差')),
                ('max_error', models.FloatField(default=0.0, help_text='最大位置误差（单位：mm）', verbose_name='最大误差')),
                ('std_error', models.FloatField(default=0.0, help_text='误差标准差（单位：mm）', verbose_name='标准差')),
                ('is_passed', models.BooleanField(default=False, help_text='验证是否通过（误差在阈值内）', verbose_name='是否通过')),
                ('error_threshold', models.FloatField(default=5.0, help_text='验证通过的误差阈值（单位：mm）', verbose_name='误差阈值')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='vision.handeyecalibration', verbose_name='所属标定')),
            ],
            options={
                'verbose_name': '手眼标定验证',
                'verbose_name_plural': '手眼标定验证',
                'db_table': 'vision_hand_eye_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='handeyecalibration',
            index=models.Index(fields=['robot_device', 'camera_device', 'is_active'], name='vision_hand_robot_d_ea304f_idx'),
        ),
        migrations.AddConstraint(
            model_name='handeyecalibration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('robot_device', 'camera_device'), name='unique_active_calibration_per_robot_camera'),
        ),
        migrations.AddIndex(
            model_name='handeyecalibrationsample',
            index=models.Index(fields=['calibration', 'sample_index'], name='vision_hand_calibra_305cbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='handeyecalibrationsample',
            constraint=models.UniqueConstraint(fields=('calibration', 'sample_index'), name='unique_sample_index_per_calibration'),
        ),
        migrations.AddIndex(
            model_name='handeyeverificationresult',
            index=models.Index(fields=['calibration', '-created_at'], name='vision_hand_calibra_efcec9_idx'),
        ),
    ]
