# Generated by Django 5.2.8 on 2026-07-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0012_racklocationrecipe_capture_pose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROI3DTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='例如：标准3层料架模板、5层高料架模板', max_length=128, unique=True, verbose_name='模板名称')),
                ('rack_type', models.CharField(db_index=True, help_text='适用的料架类型', max_length=64, verbose_name='料架类型')),
                ('layer_count', models.PositiveIntegerField(default=3, help_text='模板的层数', verbose_name='层数')),
                ('roi_configs', models.JSONField(default=list, help_text='包含所有层的ROI配置列表', verbose_name='ROI配置')),
                ('default_algorithm_params', models.JSONField(blank=True, default=dict, help_text='模板的默认算法参数', verbose_name='默认算法参数')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活此模板', verbose_name='激活')),
                ('description', models.TextField(blank=True, help_text='模板的详细说明', verbose_name='描述')),
            ],
            options={
                'verbose_name': '3D ROI模板',
                'verbose_name_plural': '3D ROI模板',
                'db_table': 'vision_roi_3d_template',
                'ordering': ['rack_type', 'layer_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RackLocationROI3DEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roi_name', models.CharField(help_text='例如：第2层主ROI、第2层支撑面ROI', max_length=128, verbose_name='名称')),
                ('roi_type', models.CharField(choices=[('MAIN', '主定位ROI'), ('SUPPORT_PLANE', '支撑面ROI'), ('FRONT_EDGE', '前边缘ROI'), ('PILLAR', '立柱ROI'), ('SIDE_EDGE', '侧边缘ROI'), ('CUSTOM', '自定义ROI')], default='MAIN', help_text='ROI的功能类型', max_length=32, verbose_name='ROI类型')),
                ('position_no', models.PositiveIntegerField(db_index=True, default=1, help_text='对应RackLocationRecipe的position_no', verbose_name='点位序号')),
                ('layer_no', models.PositiveIntegerField(db_index=True, help_text='料架的第几层（1, 2, 3...）', verbose_name='层号')),
                ('coordinate_system', models.CharField(choices=[('ROBOT', '机器人基坐标系'), ('CAMERA', '相机坐标系'), ('RACK', '料架坐标系')], default='ROBOT', help_text='ROI坐标所在的坐标系', max_length=32, verbose_name='坐标系')),
                ('x_min', models.DecimalField(decimal_places=3, help_text='X轴最小值（mm）', max_digits=10, verbose_name='X最小值')),
                ('x_max', models.DecimalField(decimal_places=3, help_text='X轴最大值（mm）', max_digits=10, verbose_name='X最大值')),
                ('y_min', models.DecimalField(decimal_places=3, help_text='Y轴最小值（mm）', max_digits=10, verbose_name='Y最小值')),
                ('y_max', models.DecimalField(decimal_places=3, help_text='Y轴最大值（mm）', max_digits=10, verbose_name='Y最大值')),
                ('z_min', models.DecimalField(decimal_places=3, help_text='Z轴最小值（mm）', max_digits=10, verbose_name='Z最小值')),
                ('z_max', models.DecimalField(decimal_places=3, help_text='Z轴最大值（mm）', max_digits=10, verbose_name='Z最大值')),
                ('priority', models.IntegerField(default=100, help_text='数字越小优先级越高，同层同类型ROI按优先级使用', verbose_name='优先级')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='计算偏移时的权重（0.0-1.0）', max_digits=5, verbose_name='权重')),
                ('algorithm_params', models.JSONField(blank=True, default=dict, help_text='特定于ROI类型的算法参数，例如：平面拟合阈值、边缘检测参数等', verbose_name='算法参数')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用此ROI', verbose_name='启用')),
                ('description', models.TextField(blank=True, help_text='ROI的详细说明', verbose_name='描述')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_rois_3d', to='vision.racklocationrecipe', verbose_name='所属配方')),
            ],
            options={
                'verbose_name': '3D ROI配方',
                'verbose_name_plural': '3D ROI配方',
                'db_table': 'vision_rack_location_roi_3d_enhanced',
                'ordering': ['recipe', 'position_no', 'layer_no', 'roi_type', 'priority'],
                'indexes': [models.Index(fields=['recipe', 'position_no', 'layer_no', 'enabled'], name='vision_rack_recipe__f3488b_idx'), models.Index(fields=['recipe', 'layer_no', 'roi_type', 'enabled'], name='vision_rack_recipe__c2bace_idx'), models.Index(fields=['roi_type', 'enabled'], name='vision_rack_roi_typ_f3a804_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x_min__lt', models.F('x_max'))), name='enhanced_roi_x_min_lt_x_max'), models.CheckConstraint(condition=models.Q(('y_min__lt', models.F('y_max'))), name='enhanced_roi_y_min_lt_y_max'), models.CheckConstraint(condition=models.Q(('z_min__lt', models.F('z_max'))), name='enhanced_roi_z_min_lt_z_max'), models.CheckConstraint(condition=models.Q(('weight__gte', 0.0), ('weight__lte', 1.0)), name='enhanced_roi_weight_range')],
            },
        ),
    ]
