# Generated by Django 6.0.6 on 2026-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0015_add_plc_written_at_to_rack_location_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racklocationresult',
            name='plc_written_at',
        ),
        migrations.AddField(
            model_name='racklocationrecipe',
            name='local_template_built_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='标准模板建立时间'),
        ),
        migrations.AddField(
            model_name='racklocationrecipe',
            name='local_template_std',
            field=models.JSONField(blank=True, help_text='示教阶段建立的标准局部坐标系模板，包含 T_std(4x4)、三平面参数等。由 RigidBodyCompensationAlgorithm.teach_mode_build_template() 生成并序列化存储。', null=True, verbose_name='标准局部3D模板'),
        ),
        migrations.AddField(
            model_name='racklocationrecipe',
            name='local_template_version',
            field=models.CharField(default='v2_rigid_body', help_text='用于未来算法升级时的版本兼容判断', max_length=32, verbose_name='模板算法版本'),
        ),
        migrations.AddField(
            model_name='racklocationrecipe',
            name='roi_weights',
            field=models.JSONField(blank=True, default=dict, help_text='{"w1": 0.5, "w3": 0.5}，控制区域1和区域3在Z轴加权平均中的权重', verbose_name='区域权重配置'),
        ),
    ]
