# Generated by Django 6.0.6 on 2026-08-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0019_alter_visionrecipe_recipe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoamRackSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='规格名称')),
                ('rack_type', models.CharField(help_text='唯一标识，用于关联 VisionRecipe.rack_type，例如 "3-LAYER"', max_length=64, unique=True, verbose_name='料架类型码')),
                ('layer_count', models.PositiveIntegerField(default=3, verbose_name='料架层数')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '料架规格档案',
                'verbose_name_plural': '料架规格档案',
                'ordering': ['layer_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoamProductLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=128, verbose_name='产品编码')),
                ('product_name', models.CharField(blank=True, max_length=128, verbose_name='产品名称')),
                ('qty_per_layer', models.PositiveIntegerField(default=5, verbose_name='每层槽位数')),
                ('rack_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_layouts', to='vision.foamrackspec', verbose_name='料架规格')),
            ],
            options={
                'verbose_name': '产品泡棉布局档案',
                'verbose_name_plural': '产品泡棉布局档案',
                'ordering': ['rack_spec', 'product_code'],
                'unique_together': {('rack_spec', 'product_code')},
            },
        ),
    ]
