# Generated by Django 6.0.6 on 2026-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0020_foam_rack_spec_product_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foamproductlayout',
            options={'ordering': ['rack_spec', 'product_code'], 'verbose_name': '2D泡棉产品布局'},
        ),
        migrations.AlterModelOptions(
            name='foamrackspec',
            options={'ordering': ['layer_count', 'name'], 'verbose_name': '2D泡棉料架规格'},
        ),
        migrations.AlterField(
            model_name='foamproductlayout',
            name='product_code',
            field=models.CharField(max_length=128, verbose_name='产品码'),
        ),
        migrations.AlterField(
            model_name='foamproductlayout',
            name='qty_per_layer',
            field=models.PositiveIntegerField(default=5, verbose_name='每层产品数'),
        ),
        migrations.AlterField(
            model_name='foamrackspec',
            name='rack_type',
            field=models.CharField(help_text='与 VisionRecipe.rack_type 保持一致', max_length=64, unique=True, verbose_name='料架类型码'),
        ),
    ]
