# Generated by Django 6.0.6 on 2026-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(max_length=64, unique=True)),
                ('product_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='OPEN', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack_code', models.CharField(max_length=64, unique=True)),
                ('rack_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='EMPTY', max_length=32)),
                ('position_side', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RackRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('rack_type', models.CharField(max_length=64)),
                ('layer_count', models.PositiveIntegerField(default=0)),
                ('quantity_per_layer', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('layer_height', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('layer_spacing', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tolerance_x', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tolerance_y', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tolerance_z', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=128, unique=True)),
                ('current_state', models.CharField(choices=[('CREATED', '已创建'), ('INJECTION_PICKED', '注塑已取件'), ('MARKING_READY', '已到打标位'), ('MARKED', '已打标'), ('BARCODE_READ', '条码已读取'), ('MES_UPLOADED', 'MES已上传'), ('HANDOVER_WAITING', '待交接'), ('HANDOVER_ROBOT_READY', '装箱机器人已就绪'), ('HANDOVER_GRIPPED', '装箱机器人已抓牢'), ('INJECTION_RELEASED', '注塑机器人已释放'), ('RACK_SCANNED', '料框已扫码'), ('RECIPE_LOADED', '配方已加载'), ('RACK_LOCATING', '料架定位中'), ('RACK_LOCATED', '料架定位完成'), ('RECIPE_VERIFIED', '配方校验通过'), ('BOXING', '装箱中'), ('FOAM_PICKING', '泡棉抓取中'), ('FOAM_ATTACHING', '泡棉贴附中'), ('FOAM_INSPECTING', '泡棉检测中'), ('COMPLETED', '工序完成'), ('LOCKED', '异常锁定'), ('FAILED', '流程失败')], default='CREATED', max_length=64)),
                ('mark_status', models.CharField(default='PENDING', max_length=32)),
                ('mes_upload_status', models.CharField(default='PENDING', max_length=32)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionbatch')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='current_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.rackrecipe'),
        ),
    ]
