# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark_status',
            field=models.CharField(choices=[('PENDING', '待打标'), ('MARKED', '已打标'), ('FAILED', '打标失败')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='mes_upload_status',
            field=models.CharField(choices=[('PENDING', '待上传'), ('UPLOADED', '已上传'), ('FAILED', '上传失败')], default='PENDING', max_length=32),
        ),
    ]
