# Generated by Django 6.0.6 on 2026-08-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_rack_recipe_vision_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defect_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='标记残次时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='defect_reason',
            field=models.CharField(blank=True, max_length=128, verbose_name='残次原因'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_defective',
            field=models.BooleanField(default=False, verbose_name='是否残次品'),
        ),
        migrations.AddField(
            model_name='product',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='production.product', verbose_name='替换的新合格品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_state',
            field=models.CharField(choices=[('CREATED', '已创建'), ('INJECTION_PICKED', '注塑已取件'), ('MARKING_READY', '已到打标位'), ('MARKED', '已打标'), ('BARCODE_READ', '条码已读取'), ('MES_UPLOADED', 'MES已上传'), ('HANDOVER_WAITING', '待交接'), ('HANDOVER_ROBOT_READY', '装箱机器人已就绪'), ('HANDOVER_GRIPPED', '装箱机器人已抓牢'), ('INJECTION_RELEASED', '注塑机器人已释放'), ('RACK_SCAN_READY', '料框扫码就绪'), ('RACK_SCANNED', '料框已扫码'), ('RECIPE_LOADED', '配方已加载'), ('RACK_LOCATING', '料架定位中'), ('RACK_LOCATED', '料架定位完成'), ('RECIPE_VERIFIED', '配方校验通过'), ('BOXING', '装箱中'), ('FOAM_PICKING', '泡棉抓取中'), ('FOAM_ATTACHING', '泡棉贴附中'), ('FOAM_INSPECTING', '泡棉检测中'), ('COMPLETED', '工序完成'), ('DEFECTIVE', '残次品/报废'), ('LOCKED', '异常锁定'), ('FAILED', '流程失败')], default='CREATED', max_length=64),
        ),
    ]
