"""append locate_all and _analyse_side to rack_locator.py"""

append_code = (
    "\n"
    "    # ------------------------------------------------------------------\n"
    "    # locate_all: 单次拍摄覆盖双料架（硬件确认）\n"
    "    # ------------------------------------------------------------------\n"
    "\n"
    "    def locate_all(self, *, recipe=None, calibration_profile=None,\n"
    "                   simulated_offsets_map=None, product_code=''):\n"
    "        \"\"\"单次拍摄同时覆盖左右两个料架，返回双侧定位结果。\n"
    "\n"
    "        硬件确认：3D 相机一次拍摄即可覆盖全部料架区域，算法从同一张深度图\n"
    "        中分别解析左侧区域和右侧区域，输出各自 X/Y/Z 偏差与 plc_payload。\n"
    "        \"\"\"\n"
    "        if not self.simulate:\n"
    "            raise NotImplementedError('真实深度相机 locate_all 尚未接入')\n"
    "\n"
    "        sides = ('LEFT', 'RIGHT')\n"
    "        offsets_map = simulated_offsets_map or {}\n"
    "        layer_count = (\n"
    "            int(recipe.layer_count)\n"
    "            if recipe and getattr(recipe, 'layer_count', None)\n"
    "            else self.config.layer_count_expected\n"
    "        )\n"
    "\n"
    "        # 1. 单次生成覆盖双料架的宽幅深度图\n"
    "        dual_img, rois = image_io.generate_depth_scene_both(layer_count=layer_count)\n"
    "        original_path, w, h = image_io.save_image(dual_img, 'depth_both_raw')\n"
    "\n"
    "        # 2. 从同一张图中分别解析各侧数据\n"
    "        all_side_data = {}\n"
    "        for side in sides:\n"
    "            all_side_data[side] = self._analyse_side(\n"
    "                side=side, recipe=recipe, calibration_profile=calibration_profile,\n"
    "                product_code=product_code, simulated_offsets=offsets_map.get(side),\n"
    "            )\n"
    "\n"
    "        # 3. 在合并图上绘制双侧标注后归档\n"
    "        annotated = image_io.annotate_depth_both(\n"
    "            dual_img, rois, all_side_data, layer_count=layer_count,\n"
    "        )\n"
    "        result_path, _, _ = image_io.save_image(\n"
    "            annotated, 'depth_both_result', rel_dir='vision/results',\n"
    "        )\n"
    "\n"
    "        results = {}\n"
    "        for side in sides:\n"
    "            results[side] = {\n"
    "                **all_side_data[side],\n"
    "                'original_image': original_path,\n"
    "                'result_image': result_path,\n"
    "                'image_width': w,\n"
    "                'image_height': h,\n"
    "            }\n"
    "\n"
    "        return {\n"
    "            'LEFT': results['LEFT'],\n"
    "            'RIGHT': results['RIGHT'],\n"
    "            'original_image': original_path,\n"
    "            'result_image': result_path,\n"
    "            'image_width': w,\n"
    "            'image_height': h,\n"
    "        }\n"
    "\n"
    "    def _analyse_side(self, *, side, recipe=None, calibration_profile=None,\n"
    "                      product_code='', simulated_offsets=None):\n"
    "        \"\"\"从已采集的深度图中解析单侧料架数据（纯数值计算，不生成图像）。\"\"\"\n"
    "        cfg = self.config\n"
    "        defaults = {\n"
    "            'LEFT':  {'offset_x': 1.2,  'offset_y': -0.8, 'offset_z': 0.5},\n"
    "            'RIGHT': {'offset_x': -1.0, 'offset_y':  0.6, 'offset_z': -0.4},\n"
    "        }\n"
    "        raw = simulated_offsets or defaults.get(side, defaults['LEFT'])\n"
    "        offsets = {k: round(float(v), 3) for k, v in raw.items()\n"
    "                   if k in ('offset_x', 'offset_y', 'offset_z')}\n"
    "\n"
    "        if recipe is not None:\n"
    "            layer_count = (int(recipe.layer_count)\n"
    "                           if getattr(recipe, 'layer_count', None)\n"
    "                           else cfg.layer_count_expected)\n"
    "            nominal_height  = float(recipe.layer_height)\n"
    "            nominal_spacing = float(recipe.layer_spacing)\n"
    "        else:\n"
    "            layer_count     = cfg.layer_count_expected\n"
    "            nominal_height  = 120.0\n"
    "            nominal_spacing = 150.0\n"
    "\n"
    "        rng = random.Random(hash(side) % (2 ** 32))\n"
    "\n"
    "        def noisy(base):\n"
    "            return round(base + rng.gauss(0, cfg.noise_std_mm), 3)\n"
    "\n"
    "        layer_heights  = [noisy(nominal_height)  for _ in range(layer_count)]\n"
    "        layer_spacings = [noisy(nominal_spacing) for _ in range(layer_count - 1)]\n"
    "        measured_height  = round(sum(layer_heights) / len(layer_heights), 3)\n"
    "        measured_spacing = (\n"
    "            round(sum(layer_spacings) / len(layer_spacings), 3)\n"
    "            if layer_spacings else nominal_spacing\n"
    "        )\n"
    "\n"
    "        variance = (\n"
    "            sum((h - measured_height) ** 2 for h in layer_heights) / layer_count\n"
    "            if layer_count > 1 else 0\n"
    "        )\n"
    "        confidence = round(max(0.70, 0.98 - variance / 25), 4) if layer_count > 1 else 0.95\n"
    "        is_success = confidence >= cfg.min_confidence\n"
    "\n"
    "        recipe_matched = True\n"
    "        if recipe is not None:\n"
    "            tol = max(float(getattr(recipe, 'tolerance_z', 1)), 1.0)\n"
    "            recipe_matched = (\n"
    "                abs(measured_height - nominal_height) <= tol\n"
    "                and abs(measured_spacing - nominal_spacing) <= tol\n"
    "            )\n"
    "\n"
    "        plc_payload = {\n"
    "            'side': side,\n"
    "            'offset_x': offsets['offset_x'],\n"
    "            'offset_y': offsets['offset_y'],\n"
    "            'offset_z': offsets['offset_z'],\n"
    "            'layer_count': layer_count,\n"
    "            'layer_heights': layer_heights,\n"
    "            'layer_spacings': layer_spacings,\n"
    "            'confidence': confidence,\n"
    "            'recipe_matched': recipe_matched,\n"
    "            'product_code': product_code,\n"
    "        }\n"
    "\n"
    "        return {\n"
    "            'side': side,\n"
    "            'offset_x': offsets['offset_x'],\n"
    "            'offset_y': offsets['offset_y'],\n"
    "            'offset_z': offsets['offset_z'],\n"
    "            'layer_count': layer_count,\n"
    "            'layer_heights': layer_heights,\n"
    "            'layer_spacings': layer_spacings,\n"
    "            'measured_layer_height':  measured_height,\n"
    "            'measured_layer_spacing': measured_spacing,\n"
    "            'confidence': confidence,\n"
    "            'recipe_matched': recipe_matched,\n"
    "            'is_success': is_success,\n"
    "            'plc_payload': plc_payload,\n"
    "            'pillar_roi': None,\n"
    "            'region_roi': None,\n"
    "            'result_data': {\n"
    "                'algorithm': 'simulated_rack_locator_v2',\n"
    "                'scan_mode': 'single_shot_dual_rack',\n"
    "                'calibration': getattr(calibration_profile, 'version', None),\n"
    "                'layer_heights': layer_heights,\n"
    "                'layer_spacings': layer_spacings,\n"
    "                'confidence': confidence,\n"
    "                'plc_payload': plc_payload,\n"
    "            },\n"
    "        }\n"
)

with open(r'd:\workspace2\AutomaticOrder\apps\vision\algorithms\rack_locator.py',
          'a', encoding='utf-8') as f:
    f.write(append_code)
print('done')
