# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PLC', 'PLC'), ('INJECTION_ROBOT', '注塑取件机器人'), ('BOXING_ROBOT', '装箱机器人'), ('SCANNER', '扫码枪'), ('DEPTH_CAMERA', '深度相机'), ('INSPECT_CAMERA', '固定检测相机'), ('LASER_MARKER', '激光打标机'), ('FOAM_SENSOR', '泡棉距离传感器')], max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', '在线'), ('OFFLINE', '离线'), ('ALARM', '报警'), ('DISABLED', '禁用'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='devicesignalrecord',
            name='direction',
            field=models.CharField(choices=[('IN', '输入'), ('OUT', '输出')], default='IN', max_length=16),
        ),
    ]
