# Generated by Django 6.0.6 on 2026-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
