#define MYPROJECT_VERSION_MAJOR RVC_VERSION_MAJOR
#define MYPROJECT_VERSION_MINOR RVC_VERSION_MINOR
#define MYPROJECT_VERSION_PATCH RVC_VERSION_PATCH
#define MYPROJECT_VERSION_TWEAK 0

#define MYPROJECT_COMPANY_NAME "RVBUST, Inc"
#define MYPROJECT_FILE_DESCRIPTION "RVBUST RVC C SDK "
#define MYPROJECT_FILE_VERSION RVCSDK_VERSION
#define MYPROJECT_INTERNAL_NAME "MYPROJECT_INTERNAL_NAME"
#define MYPROJECT_LEGAL_COPYRIGHT "Copyright (c) RVBUST, Inc"
#define MYPROJECT_ORIGINAL_FILENAME "RVC_C.dll"
#define MYPROJECT_PRODUCT_NAME "RVBUST RVC C SDK"
#define MYPROJECT_PRODUCT_VERSION MYPROJECT_FILE_VERSION
