# Generated by Django 6.0.6 on 2026-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.CharField(blank=True, max_length=64)),
                ('current_state', models.CharField(choices=[('CREATED', '已创建'), ('INJECTION_PICKED', '注塑已取件'), ('MARKING_READY', '已到打标位'), ('MARKED', '已打标'), ('BARCODE_READ', '条码已读取'), ('MES_UPLOADED', 'MES已上传'), ('HANDOVER_WAITING', '待交接'), ('HANDOVER_ROBOT_READY', '装箱机器人已就绪'), ('HANDOVER_GRIPPED', '装箱机器人已抓牢'), ('INJECTION_RELEASED', '注塑机器人已释放'), ('RACK_SCANNED', '料框已扫码'), ('RECIPE_LOADED', '配方已加载'), ('RACK_LOCATING', '料架定位中'), ('RACK_LOCATED', '料架定位完成'), ('RECIPE_VERIFIED', '配方校验通过'), ('BOXING', '装箱中'), ('FOAM_PICKING', '泡棉抓取中'), ('FOAM_ATTACHING', '泡棉贴附中'), ('FOAM_INSPECTING', '泡棉检测中'), ('COMPLETED', '工序完成'), ('LOCKED', '异常锁定'), ('FAILED', '流程失败')], default='CREATED', max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('from_state', models.CharField(blank=True, max_length=64)),
                ('to_state', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='SYSTEM', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.workflowinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
