# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowevent',
            name='source',
            field=models.CharField(choices=[('PLC', 'PLC'), ('MES', 'MES'), ('VISION', '视觉'), ('OPERATOR', '人工'), ('SYSTEM', '系统')], default='SYSTEM', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('STAGE_ONE', '阶段一-注塑下线与打标'), ('STAGE_TWO', '阶段二-空中交接'), ('STAGE_THREE', '阶段三-视觉装箱与泡棉'), ('DONE', '已完成')], max_length=64),
        ),
    ]
