# Generated by Django 6.0.6 on 2026-08-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_workflowinstance_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('WAIT_PRODUCT', '等待产品条码'), ('WAIT_MARK_RESET', '等待打标触发复位'), ('WAIT_RACK', '等待料框到位'), ('WAIT_RACK_RESET', '等待料框触发复位'), ('WAIT_POSITION', '等待定位触发'), ('WAIT_POSITION_RESET', '等待定位触发复位'), ('WAIT_RECIPE_VERIFY', '等待配方校验触发'), ('WAIT_RECIPE_RESET', '等待配方校验触发复位'), ('WAIT_FOAM', '等待泡棉检测触发'), ('WAIT_FOAM_RESET', '等待泡棉检测触发复位'), ('WAIT_BOXING', '等待装箱完成触发'), ('WAIT_BOXING_RESET', '等待装箱触发复位'), ('COMPLETED', '装箱已满'), ('LOCKED', '工位锁定')], db_index=True, default='WAIT_PRODUCT', max_length=32)),
                ('resume_phase', models.CharField(blank=True, choices=[('WAIT_PRODUCT', '等待产品条码'), ('WAIT_MARK_RESET', '等待打标触发复位'), ('WAIT_RACK', '等待料框到位'), ('WAIT_RACK_RESET', '等待料框触发复位'), ('WAIT_POSITION', '等待定位触发'), ('WAIT_POSITION_RESET', '等待定位触发复位'), ('WAIT_RECIPE_VERIFY', '等待配方校验触发'), ('WAIT_RECIPE_RESET', '等待配方校验触发复位'), ('WAIT_FOAM', '等待泡棉检测触发'), ('WAIT_FOAM_RESET', '等待泡棉检测触发复位'), ('WAIT_BOXING', '等待装箱完成触发'), ('WAIT_BOXING_RESET', '等待装箱触发复位'), ('COMPLETED', '装箱已满'), ('LOCKED', '工位锁定')], help_text='报警解除后回到的安全握手阶段', max_length=32)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('loaded_quantity', models.PositiveIntegerField(default=0)),
                ('positioning_matrix', models.JSONField(blank=True, default=list)),
                ('measured_layer_height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('measured_layer_spacing', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('recipe_verified', models.BooleanField(blank=True, null=True)),
                ('foam_passed', models.BooleanField(blank=True, null=True)),
                ('mes_upload_success', models.BooleanField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_cycle', to='workflow.workflowinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
