# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesrecord',
            name='action',
            field=models.CharField(choices=[('GET_RACK_RECIPE', '获取料架配方'), ('UPLOAD_PRODUCT_BARCODE', '上传产品条码'), ('UPLOAD_BOXING_RESULT', '上传装箱结果'), ('UPLOAD_VISION_RESULT', '上传视觉结果'), ('UPLOAD_ALARM', '上传报警')], max_length=64),
        ),
    ]
