# Generated by Django 5.2.8 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='level',
            field=models.CharField(choices=[('INFO', '提示'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], default='ERROR', max_length=32),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='source',
            field=models.CharField(choices=[('DEVICE', '设备通讯'), ('SCANNER', '扫码'), ('MES', 'MES'), ('VISION', '视觉检测'), ('WORKFLOW', '流程超时'), ('RECIPE', '配置校验'), ('OPERATOR', '人工')], max_length=64),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('OPEN', '新建'), ('ACKNOWLEDGED', '已确认'), ('CLOSED', '已关闭')], default='OPEN', max_length=32),
        ),
    ]
