# Generated by Django 5.2.8 on 2026-06-23 04:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMCameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('device_sn', models.CharField(blank=True, max_length=32, verbose_name='设备序列号')),
                ('frame_rate', models.IntegerField(default=10, help_text='帧/秒', verbose_name='帧率')),
                ('exposure_time', models.IntegerField(default=1000, help_text='微秒', verbose_name='曝光时间')),
                ('trigger_mode', models.CharField(choices=[('ACTIVE', '主动模式'), ('SOFT', '软触发'), ('HARD', '硬触发')], default='ACTIVE', max_length=20, verbose_name='触发模式')),
                ('confidence_filter_enable', models.BooleanField(default=True, verbose_name='置信度滤波')),
                ('confidence_threshold', models.IntegerField(default=15, verbose_name='置信度阈值')),
                ('flying_pixels_filter_enable', models.BooleanField(default=True, verbose_name='飞点滤波')),
                ('flying_pixels_threshold', models.IntegerField(default=5, verbose_name='飞点阈值')),
                ('spatial_filter_enable', models.BooleanField(default=True, verbose_name='空间滤波')),
                ('spatial_threshold', models.IntegerField(default=5, verbose_name='空间阈值')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DM相机配置',
                'verbose_name_plural': 'DM相机配置',
                'db_table': 'dm_camera_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DMCameraSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(max_length=32, verbose_name='设备序列号')),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='设备IP')),
                ('status', models.CharField(choices=[('IDLE', '空闲'), ('CONNECTED', '已连接'), ('STREAMING', '采集中'), ('ERROR', '错误')], default='IDLE', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='连接时间')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='断开时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dm_camera.dmcameraconfig', verbose_name='使用配置')),
            ],
            options={
                'verbose_name': 'DM相机会话',
                'verbose_name_plural': 'DM相机会话',
                'db_table': 'dm_camera_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DMCaptureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(choices=[('DEPTH', '深度图'), ('IR', 'IR图'), ('POINTCLOUD', '点云'), ('RGB', 'RGB图')], max_length=20, verbose_name='帧类型')),
                ('frame_index', models.IntegerField(default=0, verbose_name='帧序号')),
                ('width', models.IntegerField(verbose_name='宽度')),
                ('height', models.IntegerField(verbose_name='高度')),
                ('temperature_chip', models.FloatField(blank=True, null=True, verbose_name='芯片温度')),
                ('temperature_laser1', models.FloatField(blank=True, null=True, verbose_name='激光器1温度')),
                ('temperature_laser2', models.FloatField(blank=True, null=True, verbose_name='激光器2温度')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='dm_camera/captures/%Y/%m/%d/', verbose_name='数据文件')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='dm_camera/previews/%Y/%m/%d/', verbose_name='预览图')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_records', to='dm_camera.dmcameraconfig', verbose_name='使用配置')),
            ],
            options={
                'verbose_name': 'DM采集记录',
                'verbose_name_plural': 'DM采集记录',
                'db_table': 'dm_camera_capture',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at'], name='dm_camera_c_capture_d474a7_idx'), models.Index(fields=['frame_type'], name='dm_camera_c_frame_t_c2085a_idx')],
            },
        ),
    ]
